### ISSUE TITLE
back-to-top button

### ISSUE THREAD

**Issue by jobayerarman** [Innovi/wash-my-photo#12]
need a **back-to-top** button for better scroll navigation. Check [this repo](https://github.com/jobayerarman/jobayerarman.github.io/blob/master/src/js/script.js#L106) and [CodyHouse](https://codyhouse.co/gem/back-to-top/) for reference.

**Comment by jobayerarman** [comment]
Check the [HTML snippet](https://github.com/jobayerarman/jobayerarman.github.io/blob/master/index.html#L506)

**Comment by Omid07** [comment]
Added in #35

**Comment by jobayerarman** [comment]
adding some styles and optimizing code.

**Comment by jobayerarman** [comment]
Finalized in #39
